//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EntityValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntityValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Language.EntityValidation", typeof(EntityValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountLockout.
        /// </summary>
        public static string AccountLockout {
            get {
                return ResourceManager.GetString("AccountLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date creator.
        /// </summary>
        public static string DateCreator {
            get {
                return ResourceManager.GetString("DateCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date deleted.
        /// </summary>
        public static string DateDeleted {
            get {
                return ResourceManager.GetString("DateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modify.
        /// </summary>
        public static string DateModify {
            get {
                return ResourceManager.GetString("DateModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Publish.
        /// </summary>
        public static string IsPublish {
            get {
                return ResourceManager.GetString("IsPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Box.
        /// </summary>
        public static string MetaBox {
            get {
                return ResourceManager.GetString("MetaBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Description.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Keyword.
        /// </summary>
        public static string MetaKeyword {
            get {
                return ResourceManager.GetString("MetaKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Robot Tag.
        /// </summary>
        public static string MetaRobotTag {
            get {
                return ResourceManager.GetString("MetaRobotTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta title.
        /// </summary>
        public static string MetaTitle {
            get {
                return ResourceManager.GetString("MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RememberLogin.
        /// </summary>
        public static string RememberLogin {
            get {
                return ResourceManager.GetString("RememberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Length Too Long.
        /// </summary>
        public static string StringLengthTooLong {
            get {
                return ResourceManager.GetString("StringLengthTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnLike.
        /// </summary>
        public static string UnLike {
            get {
                return ResourceManager.GetString("UnLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCreateFail.
        /// </summary>
        public static string UserCreateFail {
            get {
                return ResourceManager.GetString("UserCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User creator.
        /// </summary>
        public static string UserCreator {
            get {
                return ResourceManager.GetString("UserCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted.
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User modify.
        /// </summary>
        public static string UserModify {
            get {
                return ResourceManager.GetString("UserModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
